### ISSUE TITLE
What about supporting Rack::Multipart::UploadedFile along with File?

### ISSUE THREAD

**Issue by IlkhamGaysin** [calebhearth/formulaic#68]
I found that this https://github.com/thoughtbot/formulaic/blob/master/lib/formulaic/form.rb#L16 enforces consumers to use `File`
 class instance while in rack apps all files are wrapped by `http://www.rubydoc.info/gems/rack/Rack/Multipart/UploadedFile`

**Comment by calebthompson** [comment]
Sure, I'd take a PR for that.

**Comment by IlkhamGaysin** [comment]
@calebthompson done, here it's https://github.com/thoughtbot/formulaic/pull/72
